name: Build Candela 3
description: Build Candela 3 for Linux

runs:
  using: composite
  steps:
    - name: Build on Ubuntu (using Docker)
      uses: addnab/docker-run-action@v3
      with:
        image: kvnnap/clang:github
        options: -v ${{github.workspace}}:/workdir -w /workdir
        run: |
          cmake -S . -B build -G "Ninja Multi-Config" -DCMAKE_INSTALL_PREFIX:PATH=$PWD/install -DBUILD_SHARED_LIBS:BOOL=ON
          cmake --build build --config Release --parallel --target install
