name: Build
on:
  push:
    branches: [ main ]
env:
  CANDELA: main # unused
  VCPKG_BINARY_SOURCES: "clear;files,${{ github.workspace }}/.vcpkg-cache,readwrite"
  VCPKG_INSTALL_OPTIONS: "--clean-after-build"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            action: ./.github/actions/build-linux
          - os: windows-2025-vs2026
            action: ./.github/actions/build-windows

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set SHA_SHORT
        id: vars
        shell: bash
        run: echo "sha_short=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_OUTPUT

      - name: Cache vcpkg binaries
        uses: actions/cache@v4
        with: # restore-keys for partial reuse
          path: .vcpkg-cache
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Build Candela 3 (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: ./.github/actions/build-linux

      - name: Build Candela 3 (Windows)
        if: matrix.os == 'windows-2025-vs2026'
        uses: ./.github/actions/build-windows
      
      - name: Push artifact
        uses: actions/upload-artifact@v7
        with:
          name: candela-3-${{ steps.vars.outputs.sha_short }}-${{ matrix.os }}
          path: install
          retention-days: 14
